/* GENERATED by tools/besties-seal.mjs — do not edit by hand.
   Ciphertext only: this file is meaningless without the password.
   Edit the plaintext master and re-run `node tools/besties-seal.mjs`. */
window.BESTIES_GUESTS={};
