#!/usr/bin/env node
/* ============================================================================
   besties-seal — turns the plaintext /besties content into a sealed payload.

   WHY THIS EXISTS
   ---------------
   The site is static (GitHub Pages). There is no server, so there is nowhere to
   check a password. The naive version — `if (typed === 'PINKYPROMISE')` — puts
   both the password AND the entire invitation in view-source, which defeats the
   whole point of a private route.

   So instead: the password IS the key. The content is encrypted with AES-GCM
   under a PBKDF2-SHA256 key derived from the password, and only the ciphertext
   ships. Before someone types the right words, the browser is holding noise.
   A wrong password isn't "rejected" — it simply cannot decrypt.

   This is not bank security (anyone with the password can share it, and the
   ciphertext is downloadable and offline-attackable). It is exactly the right
   amount of security for a party invitation, and it is strictly, provably
   better than a string comparison.

   USAGE
   -----
     node tools/besties-seal.mjs seal      besties/content.json → besties/sealed.js
     node tools/besties-seal.mjs unseal    besties/sealed.js    → besties/content.json
     node tools/besties-seal.mjs guests    besties/guests.json  → besties/guests.js
     node tools/besties-seal.mjs add "Shanaya Kapoor"     mint a personalised link

   The password comes from --pass=…, or $BESTIES_PASS, or besties/.password
   (gitignored), in that order. Default: PINKYPROMISE.
   ============================================================================ */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { webcrypto as crypto } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const P = (...p) => join(ROOT, ...p);

/* PBKDF2 rounds. 250k costs a phone ~250ms once, at unlock — unnoticeable next
   to the deliberate cinematic pause — but multiplies the cost of grinding the
   ciphertext offline by the same factor. */
const ROUNDS = 250_000;
/* The guest-lookup index is derived the same slow way rather than with a plain
   hash, so the list of invite-code hashes can't be run through a fast dictionary
   of first names. */
const GUEST_ROUNDS = 100_000;

const enc = new TextEncoder();
const dec = new TextDecoder();
const b64 = (buf) => Buffer.from(buf).toString('base64');
const unb64 = (str) => new Uint8Array(Buffer.from(str, 'base64'));

async function keyFrom(secret, salt, rounds) {
  const base = await crypto.subtle.importKey('raw', enc.encode(secret), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: rounds, hash: 'SHA-256' },
    base, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
}

async function seal(plainObj, secret, rounds = ROUNDS) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await keyFrom(secret, salt, rounds);
  const body = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(JSON.stringify(plainObj)));
  return { v: 1, r: rounds, s: b64(salt), i: b64(iv), c: b64(body) };
}

async function unseal(blob, secret) {
  const key = await keyFrom(secret, unb64(blob.s), blob.r || ROUNDS);
  const out = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(blob.i) }, key, unb64(blob.c));
  return JSON.parse(dec.decode(out));
}

/* The index a personalised link is looked up by. Same slow derivation as the
   blob itself, so an attacker holding guests.js still has to spend 100k rounds
   per guess to test "shanaya" against it. */
async function guestIndex(code) {
  const base = await crypto.subtle.importKey('raw', enc.encode(code.toLowerCase()), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: enc.encode('ssp-besties-index'), iterations: GUEST_ROUNDS, hash: 'SHA-256' }, base, 128);
  return Buffer.from(bits).toString('hex');
}

async function password(argv) {
  const flag = argv.find(a => a.startsWith('--pass='));
  if (flag) return flag.slice(7);
  if (process.env.BESTIES_PASS) return process.env.BESTIES_PASS;
  if (existsSync(P('besties/.password'))) return (await readFile(P('besties/.password'), 'utf8')).trim();
  return 'PINKYPROMISE';
}

const banner = (file) =>
  `/* GENERATED by tools/besties-seal.mjs — do not edit by hand.\n` +
  `   Ciphertext only: this file is meaningless without the password.\n` +
  `   Edit the plaintext master and re-run \`node tools/besties-seal.mjs\`. */\n`;

/* Readable random: no 0/o/1/l/i, so a code can be read aloud over the phone. */
const ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789';
const suffix = (n = 4) => Array.from(crypto.getRandomValues(new Uint8Array(n)))
  .map(b => ALPHABET[b % ALPHABET.length]).join('');
const slugify = (s) => s.toLowerCase().trim().split(/\s+/)[0].replace(/[^a-z0-9]/g, '');

async function cmdSeal(argv) {
  const pass = await password(argv);
  const content = JSON.parse(await readFile(P('besties/content.json'), 'utf8'));
  delete content._readme;
  const blob = await seal(content, pass);
  await writeFile(P('besties/sealed.js'),
    banner() + `window.BESTIES_SEALED=${JSON.stringify(blob)};\n`);
  console.log(`sealed  besties/content.json → besties/sealed.js  (password: ${pass})`);
}

async function cmdUnseal(argv) {
  const pass = await password(argv);
  const src = await readFile(P('besties/sealed.js'), 'utf8');
  const blob = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1));
  const out = await unseal(blob, pass);
  await writeFile(P('besties/content.json'), JSON.stringify(out, null, 2) + '\n');
  console.log('unsealed  besties/sealed.js → besties/content.json');
}

/* Each guest gets their OWN sealed blob, encrypted under their own invite code
   and carrying the party password inside it — so a personalised link unlocks
   without anyone typing anything, while the guest list as a whole stays shut. */
async function cmdGuests(argv) {
  const pass = await password(argv);
  if (!existsSync(P('besties/guests.json'))) {
    await writeFile(P('besties/guests.js'), banner() + 'window.BESTIES_GUESTS={};\n');
    return console.log('no besties/guests.json — wrote an empty besties/guests.js');
  }
  const list = JSON.parse(await readFile(P('besties/guests.json'), 'utf8'));
  const out = {};
  for (const g of list) {
    const record = { first: g.first || (g.name || '').split(/\s+/)[0], name: g.name || '',
                     plus_one: !!g.plus_one, notes: g.notes || '',
                     // picks a copy variant out of content.variants (e.g. "neutral")
                     voice: g.voice || null, pass };
    out[await guestIndex(g.code)] = await seal(record, g.code.toLowerCase(), GUEST_ROUNDS);
  }
  await writeFile(P('besties/guests.js'), banner() + `window.BESTIES_GUESTS=${JSON.stringify(out)};\n`);
  console.log(`sealed ${list.length} guest${list.length === 1 ? '' : 's'} → besties/guests.js`);
  for (const g of list) console.log(`  ${g.name.padEnd(24)} secretslumberparty.com/besties/${g.code}`);
}

async function cmdAdd(argv) {
  const name = argv.slice(1).filter(a => !a.startsWith('--')).join(' ');
  if (!name) return console.error('usage: node tools/besties-seal.mjs add "Shanaya Kapoor"');
  const list = existsSync(P('besties/guests.json'))
    ? JSON.parse(await readFile(P('besties/guests.json'), 'utf8')) : [];
  const code = `${slugify(name)}-${suffix()}`;
  list.push({ name, first: name.split(/\s+/)[0], code, plus_one: false, notes: '' });
  await writeFile(P('besties/guests.json'), JSON.stringify(list, null, 2) + '\n');
  await cmdGuests(argv);
  console.log(`\n  ↳ send her:  secretslumberparty.com/besties/${code}`);
}

const [cmd = 'seal', ...rest] = process.argv.slice(2);
const argv = [cmd, ...rest];
const run = { seal: cmdSeal, unseal: cmdUnseal, guests: cmdGuests, add: cmdAdd }[cmd];
if (!run) { console.error(`unknown command "${cmd}" — try: seal | unseal | guests | add`); process.exit(1); }
run(argv).catch(err => {
  if (String(err).includes('operation-specific reason') || err?.name === 'OperationError')
    console.error('could not decrypt — wrong password?');
  else console.error(err);
  process.exit(1);
});
